language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-N
  - extra
before_install:
  - chmod +x gradlew
licenses:
  - android-sdk-license-.+
  - '.+'
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
script:
- ./gradlew assembleRelease